FINALIZED = "finalized"
CONFIRMED = "confirmed"
PROCESSED = "processed"

COMMITMENT = "commitment"
TOTAL_STAKE = "totalStake"
SLOT = "slot"
BLOCKHASH = "blockhash"
PREVIOUS_BLOCKHASH = "previousBlockhash"
PARENT_SLOT = "parentSlot"
BLOCK_HEIGHT = "blockHeight"
REWARDS = "rewards"
TRANSACTIONS = "transactions"
TRANSACTION = "transaction"
BLOCK_TIME = "blockTime"
SIGNATURES = "signatures"
META = "meta"
ERR = "err"
FEE = "fee"
PRE_BALANCES = "preBalances"
POST_BALANCES = "postBalances"
MESSAGE = "message"
INSTRUCTIONS = "instructions"
ACCOUNT_KEYS = "accountKeys"
PUBKEY = "pubkey"
EXECUTABLE = "executable"
OWNER = "owner"
RENT_EPOCH = "rentEpoch"
DATA = "data"
HEADER = "header"
NUM_READONLY_SIGNED_ACCOUNTS = "numReadonlySignedAccounts"
NUM_READONLY_UNSIGNED_ACCOUNTS = "numReadonlyUnsignedAccounts"
NUM_REQUIRED_SIGNATURES = "numRequiredSignatures"
VALUE = "value"


RESULT = "result"
